name: running_historian
description: "Ğ‘ĞµĞ³Ğ¾Ğ²Ğ¾Ğ¹ Ğ³Ğ¸Ğ´ Ğ´Ğ»Ñ Ğ±ĞµĞ³ÑƒĞ½Ğ¾Ğ²"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '^3.10.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_map: ^8.2.2
  latlong2: ^0.9.1
  geolocator: ^11.1.0
  shared_preferences: ^2.2.2

  just_audio: ^0.9.46
  flutter_tts: ^4.2.3

  path_provider: ^2.0.15
  path: ^1.8.2

  hive: ^2.2.3
  hive_flutter: ^1.1.0

  flutter_background_service: ^5.0.5
  flutter_background_service_android: ^6.0.3 # ğŸ‘ˆ Ğ£Ğ¶Ğµ ĞµÑÑ‚ÑŒ

  permission_handler: ^11.0.1
  app_settings: ^5.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.4.7
  hive_generator: ^2.0.1 # ğŸ‘ˆ Ğ£Ğ¶Ğµ ĞµÑÑ‚ÑŒ

flutter:
  uses-material-design: true
  assets:
    - assets/music.mp3