name: running_historian
description: "Беговой гид для бегунов"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '^3.10.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_map: ^8.2.2
  latlong2: ^0.9.1
  geolocator: ^11.1.0
  shared_preferences: ^2.2.2
  just_audio: ^0.9.46
  flutter_tts: ^4.2.3
  path_provider: ^2.1.5  # ✅ На правильном уровне
  path: ^1.8.2
  http: ^1.2.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_background_service: ^5.0.5
  flutter_background_service_android: ^6.0.3
  permission_handler: ^11.0.1
  app_settings: ^5.1.1
  flutter_animate: ^4.5.2
  smooth_page_indicator: ^1.0.1
  crypto: ^3.0.3
  collection: ^1.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.7
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/music.mp3